In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('https://raw.githubusercontent.com/Ahtesham-Ibne-Mostafa/Machine_Etymology/main/Datasets/NCHS_-_Potentially_Excess_Deaths_from_the_Five_Leading_Causes_of_Death.csv')

In [4]:
df.head()

Year Cause of Death    State State FIPS Code  HHS Region Age Range  \
0  2005         Cancer  Alabama              AL           4      0-49   
1  2005         Cancer  Alabama              AL           4      0-49   
2  2005         Cancer  Alabama              AL           4      0-49   
3  2005         Cancer  Alabama              AL           4      0-49   
4  2005         Cancer  Alabama              AL           4      0-49   

    Benchmark         Locality  Observed Deaths  Population  Expected Deaths  \
0  2005 Fixed              All            756.0   3148377.0            451.0   
1  2005 Fixed     Metropolitan            556.0   2379871.0            341.0   
2  2005 Fixed  Nonmetropolitan            200.0    768506.0            111.0   
3  2010 Fixed              All            756.0   3148377.0            421.0   
4  2010 Fixed     Metropolitan            556.0   2379871.0            318.0   

   Potentially Excess Deaths  Percent Potentially Excess Deaths  
0                      305.0                               40.3  
1                      217.0                               39.0  
2                       89.0                               44.5  
3                      335.0                               44.3  
4                      238.0                               42.8

In [5]:
df.shape

(205920, 13)

In [6]:
df['Cause of Death'].unique()


array(['Cancer', 'Chronic Lower Respiratory Disease', 'Heart Disease',
       'Stroke', 'Unintentional Injury'], dtype=object)

In [7]:
df['Cause of Death'].value_counts()

Cancer                               41184
Chronic Lower Respiratory Disease    41184
Heart Disease                        41184
Stroke                               41184
Unintentional Injury                 41184
Name: Cause of Death, dtype: int64

In [8]:
df['State'].value_counts()

Alabama                  3960
Alaska                   3960
Montana                  3960
Nebraska                 3960
Nevada                   3960
New Hampshire            3960
New Mexico               3960
New York                 3960
North Carolina           3960
North Dakota             3960
Ohio                     3960
Oklahoma                 3960
Oregon                   3960
Pennsylvania             3960
South Carolina           3960
South Dakota             3960
Tennessee                3960
Texas                    3960
United States            3960
Utah                     3960
Vermont                  3960
Virginia                 3960
Washington               3960
West Virginia            3960
Wisconsin                3960
Missouri                 3960
Mississippi              3960
Minnesota                3960
Hawaii                   3960
Arizona                  3960
Arkansas                 3960
Delaware                 3960
California               3960
Colorado  

In [9]:
df['State FIPS Code'].value_counts()

AL    3960
AK    3960
MT    3960
NE    3960
NV    3960
NH    3960
NM    3960
NY    3960
NC    3960
ND    3960
OH    3960
OK    3960
OR    3960
PA    3960
SC    3960
SD    3960
TN    3960
TX    3960
0     3960
UT    3960
VT    3960
VA    3960
WA    3960
WV    3960
WI    3960
MO    3960
MS    3960
MN    3960
HI    3960
AZ    3960
AR    3960
DE    3960
CA    3960
CO    3960
CT    3960
NJ    3960
DC    3960
FL    3960
GA    3960
ID    3960
MI    3960
IL    3960
IN    3960
IA    3960
RI    3960
KS    3960
KY    3960
LA    3960
ME    3960
MD    3960
MA    3960
WY    3960
Name: State FIPS Code, dtype: int64

In [10]:
df['HHS Region'].value_counts()

4     31680
3     23760
8     23760
1     23760
5     23760
6     19800
10    15840
9     15840
7     15840
2      7920
0      3960
Name: HHS Region, dtype: int64

In [11]:
df.isnull().sum()

Year                                     0
Cause of Death                           0
State                                    0
State FIPS Code                          0
HHS Region                               0
Age Range                                0
Benchmark                                0
Locality                                 0
Observed Deaths                      10212
Population                            5280
Expected Deaths                      10212
Potentially Excess Deaths            10212
Percent Potentially Excess Deaths    10212
dtype: int64

In [12]:
def Chamber_of_nulls(df,target,type='mean'):
    columns_with_null = df.columns[df.isnull().any()]
    segments=df[target].unique()
    for i in segments:

        filtered_rows = df[df[target] == i]
        for j in columns_with_null:
            if type=='mean':
              new_value = filtered_rows[j].mean()
            elif type=='mode':
              new_value = filtered_rows[j].mode()
            elif type=='median':
              new_value = filtered_rows[j].median()

            filtered_null_rows = filtered_rows[filtered_rows[j].isna()]
            df.loc[filtered_null_rows.index, j] = new_value
    return df

In [13]:
feature='Cause of Death'
df=Chamber_of_nulls(df, feature)

In [14]:
df = df.drop('State FIPS Code', axis=1)

In [15]:
df.head()

Year Cause of Death    State  HHS Region Age Range   Benchmark  \
0  2005         Cancer  Alabama           4      0-49  2005 Fixed   
1  2005         Cancer  Alabama           4      0-49  2005 Fixed   
2  2005         Cancer  Alabama           4      0-49  2005 Fixed   
3  2005         Cancer  Alabama           4      0-49  2010 Fixed   
4  2005         Cancer  Alabama           4      0-49  2010 Fixed   

          Locality  Observed Deaths  Population  Expected Deaths  \
0              All            756.0   3148377.0            451.0   
1     Metropolitan            556.0   2379871.0            341.0   
2  Nonmetropolitan            200.0    768506.0            111.0   
3              All            756.0   3148377.0            421.0   
4     Metropolitan            556.0   2379871.0            318.0   

   Potentially Excess Deaths  Percent Potentially Excess Deaths  
0                      305.0                               40.3  
1                      217.0                               39.0  
2                       89.0                               44.5  
3                      335.0                               44.3  
4                      238.0                               42.8

In [16]:
df.shape

(205920, 12)

In [17]:
df.isnull().sum()

Year                                 0
Cause of Death                       0
State                                0
HHS Region                           0
Age Range                            0
Benchmark                            0
Locality                             0
Observed Deaths                      0
Population                           0
Expected Deaths                      0
Potentially Excess Deaths            0
Percent Potentially Excess Deaths    0
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205920 entries, 0 to 205919
Data columns (total 12 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   Year                               205920 non-null  int64  
 1   Cause of Death                     205920 non-null  object 
 2   State                              205920 non-null  object 
 3   HHS Region                         205920 non-null  int64  
 4   Age Range                          205920 non-null  object 
 5   Benchmark                          205920 non-null  object 
 6   Locality                           205920 non-null  object 
 7   Observed Deaths                    205920 non-null  float64
 8   Population                         205920 non-null  float64
 9   Expected Deaths                    205920 non-null  float64
 10  Potentially Excess Deaths          205920 non-null  float64
 11  Percent Potentially Excess Deaths  2059

In [19]:
df['Benchmark'].unique()

array(['2005 Fixed', '2010 Fixed', 'Floating'], dtype=object)

In [20]:
from sklearn.preprocessing import LabelEncoder                                # it helps to convert object to integer
label_encoder = LabelEncoder()


df['Cause of Death'] = label_encoder.fit_transform(df['Cause of Death'])
df['State'] = label_encoder.fit_transform(df['State'])
df['Age Range'] = label_encoder.fit_transform(df['Age Range'])
df['Benchmark'] = label_encoder.fit_transform(df['Benchmark'])
df['Locality'] = label_encoder.fit_transform(df['Locality'])

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205920 entries, 0 to 205919
Data columns (total 12 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   Year                               205920 non-null  int64  
 1   Cause of Death                     205920 non-null  int32  
 2   State                              205920 non-null  int32  
 3   HHS Region                         205920 non-null  int64  
 4   Age Range                          205920 non-null  int32  
 5   Benchmark                          205920 non-null  int32  
 6   Locality                           205920 non-null  int32  
 7   Observed Deaths                    205920 non-null  float64
 8   Population                         205920 non-null  float64
 9   Expected Deaths                    205920 non-null  float64
 10  Potentially Excess Deaths          205920 non-null  float64
 11  Percent Potentially Excess Deaths  2059

In [22]:
target = 'Cause of Death'

In [23]:
X= df.loc[:,df.columns != target]                                               # every columns goes to X except the target

Y = df[target]                                                                  # target column is Y

In [24]:
from sklearn.model_selection import train_test_split                            # X and Y is spited into text and train segments

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2)

#RandomForest Classifier

In [24]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_jobs=-1)

clf.fit(X_train, Y_train)                                                       # Fitting the training segment into the model

y_pred = clf.predict(X_test)                                                    # the model is predicting the test cases

In [25]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[8263    0   34    0   18]
 [   0 7788    0  299  171]
 [  32    0 8084    0   45]
 [   0  303    0 7775   29]
 [  21   96   35   11 8180]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      8315
           1       0.95      0.94      0.95      8258
           2       0.99      0.99      0.99      8161
           3       0.96      0.96      0.96      8107
           4       0.97      0.98      0.97      8343

    accuracy                           0.97     41184
   macro avg       0.97      0.97      0.97     41184
weighted avg       0.97      0.97      0.97     41184

Accurecy:  0.973436285936286


#ADABoost Classifier

In [26]:
from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier()

ada.fit(X_train, Y_train)

y_pred = ada.predict(X_test)

In [27]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[4429    7 3494  143  242]
 [ 402 2669  160 2424 2603]
 [1611  138 3770  442 2200]
 [ 411 1497  148 4119 1932]
 [ 441 1211  919  650 5122]]
              precision    recall  f1-score   support

           0       0.61      0.53      0.57      8315
           1       0.48      0.32      0.39      8258
           2       0.44      0.46      0.45      8161
           3       0.53      0.51      0.52      8107
           4       0.42      0.61      0.50      8343

    accuracy                           0.49     41184
   macro avg       0.50      0.49      0.49     41184
weighted avg       0.50      0.49      0.49     41184

Accurecy:  0.4882721445221445


#GradientBoosting Classifier

In [28]:

from sklearn.ensemble import GradientBoostingClassifier

GBC = GradientBoostingClassifier()

GBC.fit(X_train, Y_train)

y_pred = ada.predict(X_test)

In [29]:

print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[4429    7 3494  143  242]
 [ 402 2669  160 2424 2603]
 [1611  138 3770  442 2200]
 [ 411 1497  148 4119 1932]
 [ 441 1211  919  650 5122]]
              precision    recall  f1-score   support

           0       0.61      0.53      0.57      8315
           1       0.48      0.32      0.39      8258
           2       0.44      0.46      0.45      8161
           3       0.53      0.51      0.52      8107
           4       0.42      0.61      0.50      8343

    accuracy                           0.49     41184
   macro avg       0.50      0.49      0.49     41184
weighted avg       0.50      0.49      0.49     41184

Accurecy:  0.4882721445221445


#KN Classifier

In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)

y_pred=knn.predict(X_test)

C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [31]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[4913   88 2870   49  395]
 [ 125 2962  229 3967  975]
 [2904  227 3478   98 1454]
 [ 167 4495  273 2820  352]
 [ 902 1974 1458  474 3535]]
              precision    recall  f1-score   support

           0       0.55      0.59      0.57      8315
           1       0.30      0.36      0.33      8258
           2       0.42      0.43      0.42      8161
           3       0.38      0.35      0.36      8107
           4       0.53      0.42      0.47      8343

    accuracy                           0.43     41184
   macro avg       0.44      0.43      0.43     41184
weighted avg       0.44      0.43      0.43     41184

Accurecy:  0.429972804972805


#Naive Bayes

In [32]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train, Y_train)

y_pred = gnb.predict(X_test)

In [33]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[ 257  597  223 6705  533]
 [   9   61   79 8074   35]
 [  90  405  194 7143  329]
 [   7   41   82 7949   28]
 [   9  177  147 7899  111]]
              precision    recall  f1-score   support

           0       0.69      0.03      0.06      8315
           1       0.05      0.01      0.01      8258
           2       0.27      0.02      0.04      8161
           3       0.21      0.98      0.35      8107
           4       0.11      0.01      0.02      8343

    accuracy                           0.21     41184
   macro avg       0.26      0.21      0.10     41184
weighted avg       0.27      0.21      0.10     41184

Accurecy:  0.20813908313908314


#SVM Classifier

In [ ]:
from sklearn.svm import SVC

svm_classifier = SVC(kernel='linear')

svm_classifier.fit(X_train, Y_train)

y_pred = svm_classifier.predict(X_test)

In [ ]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

#Logitic Regression

In [25]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 0)
lr.fit(X_train, Y_train)
y_pred = lr.predict(X_test)

In [28]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[5414 1068 1022  347  421]
 [ 685 2000  612 3952  847]
 [2875 1362 2778  693  586]
 [ 477 2212  109 5020  474]
 [ 298 1645 2651  156 3480]]
              precision    recall  f1-score   support

           0       0.56      0.65      0.60      8272
           1       0.24      0.25      0.24      8096
           2       0.39      0.33      0.36      8294
           3       0.49      0.61      0.54      8292
           4       0.60      0.42      0.50      8230

    accuracy                           0.45     41184
   macro avg       0.46      0.45      0.45     41184
weighted avg       0.46      0.45      0.45     41184

Accurecy:  0.4538655788655789


#CAT Boosting

In [29]:
!pip install catboost

In [30]:
from catboost import CatBoostClassifier

# Create a CatBoostClassifier
model = CatBoostClassifier()

# Fit the model to the training data
model.fit(X_train, Y_train)

# Make predictions on test data
y_pred = model.predict(X_test)

Learning rate set to 0.102655
0:	learn: 1.5299271	total: 207ms	remaining: 3m 26s
1:	learn: 1.4677876	total: 256ms	remaining: 2m 7s
2:	learn: 1.4138405	total: 304ms	remaining: 1m 41s
3:	learn: 1.3664972	total: 350ms	remaining: 1m 27s
4:	learn: 1.3256191	total: 394ms	remaining: 1m 18s
5:	learn: 1.2847208	total: 451ms	remaining: 1m 14s
6:	learn: 1.2545636	total: 498ms	remaining: 1m 10s
7:	learn: 1.2243104	total: 544ms	remaining: 1m 7s
8:	learn: 1.1941423	total: 590ms	remaining: 1m 5s
9:	learn: 1.1724340	total: 636ms	remaining: 1m 2s
10:	learn: 1.1454672	total: 686ms	remaining: 1m 1s
11:	learn: 1.1241453	total: 731ms	remaining: 1m
12:	learn: 1.1037531	total: 785ms	remaining: 59.6s
13:	learn: 1.0868366	total: 828ms	remaining: 58.3s
14:	learn: 1.0672740	total: 876ms	remaining: 57.5s
15:	learn: 1.0514929	total: 923ms	remaining: 56.8s
16:	learn: 1.0340745	total: 969ms	remaining: 56.1s
17:	learn: 1.0216259	total: 1.01s	remaining: 55s
18:	learn: 1.0084872	total: 1.05s	remaining: 54.4s
19:	learn:

In [31]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[8222    0   10    0   40]
 [   0 7041    1  678  376]
 [  13    0 8148    0  133]
 [   0  493    0 7781   18]
 [  74  207   65   33 7851]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      8272
           1       0.91      0.87      0.89      8096
           2       0.99      0.98      0.99      8294
           3       0.92      0.94      0.93      8292
           4       0.93      0.95      0.94      8230

    accuracy                           0.95     41184
   macro avg       0.95      0.95      0.95     41184
weighted avg       0.95      0.95      0.95     41184

Accurecy:  0.9480137917637917
