<a href="https://colab.research.google.com/github/Ahtesham-Ibne-Mostafa/Machine_Etymology/blob/main/Cause_of_death.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/Ahtesham-Ibne-Mostafa/Machine_Etymology/main/Datasets/NCHS_-_Potentially_Excess_Deaths_from_the_Five_Leading_Causes_of_Death.csv')

In [3]:
df.head()

Year Cause of Death    State State FIPS Code  HHS Region Age Range  \
0  2005         Cancer  Alabama              AL           4      0-49   
1  2005         Cancer  Alabama              AL           4      0-49   
2  2005         Cancer  Alabama              AL           4      0-49   
3  2005         Cancer  Alabama              AL           4      0-49   
4  2005         Cancer  Alabama              AL           4      0-49   

    Benchmark         Locality  Observed Deaths  Population  Expected Deaths  \
0  2005 Fixed              All            756.0   3148377.0            451.0   
1  2005 Fixed     Metropolitan            556.0   2379871.0            341.0   
2  2005 Fixed  Nonmetropolitan            200.0    768506.0            111.0   
3  2010 Fixed              All            756.0   3148377.0            421.0   
4  2010 Fixed     Metropolitan            556.0   2379871.0            318.0   

   Potentially Excess Deaths  Percent Potentially Excess Deaths  
0                      305.0                               40.3  
1                      217.0                               39.0  
2                       89.0                               44.5  
3                      335.0                               44.3  
4                      238.0                               42.8

In [4]:
df.shape

(205920, 13)

In [5]:
df['Cause of Death'].unique()


array(['Cancer', 'Chronic Lower Respiratory Disease', 'Heart Disease',
       'Stroke', 'Unintentional Injury'], dtype=object)

In [6]:
df['Cause of Death'].value_counts()

Cancer                               41184
Chronic Lower Respiratory Disease    41184
Heart Disease                        41184
Stroke                               41184
Unintentional Injury                 41184
Name: Cause of Death, dtype: int64

In [14]:
df['State'].value_counts()

Alabama                  3960
Alaska                   3960
Montana                  3960
Nebraska                 3960
Nevada                   3960
New Hampshire            3960
New Mexico               3960
New York                 3960
North Carolina           3960
North Dakota             3960
Ohio                     3960
Oklahoma                 3960
Oregon                   3960
Pennsylvania             3960
South Carolina           3960
South Dakota             3960
Tennessee                3960
Texas                    3960
United States            3960
Utah                     3960
Vermont                  3960
Virginia                 3960
Washington               3960
West Virginia            3960
Wisconsin                3960
Missouri                 3960
Mississippi              3960
Minnesota                3960
Hawaii                   3960
Arizona                  3960
Arkansas                 3960
Delaware                 3960
California               3960
Colorado  

In [15]:
df['State FIPS Code'].value_counts()

AL    3960
AK    3960
MT    3960
NE    3960
NV    3960
NH    3960
NM    3960
NY    3960
NC    3960
ND    3960
OH    3960
OK    3960
OR    3960
PA    3960
SC    3960
SD    3960
TN    3960
TX    3960
0     3960
UT    3960
VT    3960
VA    3960
WA    3960
WV    3960
WI    3960
MO    3960
MS    3960
MN    3960
HI    3960
AZ    3960
AR    3960
DE    3960
CA    3960
CO    3960
CT    3960
NJ    3960
DC    3960
FL    3960
GA    3960
ID    3960
MI    3960
IL    3960
IN    3960
IA    3960
RI    3960
KS    3960
KY    3960
LA    3960
ME    3960
MD    3960
MA    3960
WY    3960
Name: State FIPS Code, dtype: int64

In [16]:
df['HHS Region'].value_counts()

4     31680
3     23760
8     23760
1     23760
5     23760
6     19800
10    15840
9     15840
7     15840
2      7920
0      3960
Name: HHS Region, dtype: int64

In [7]:
df.isnull().sum()

Year                                     0
Cause of Death                           0
State                                    0
State FIPS Code                          0
HHS Region                               0
Age Range                                0
Benchmark                                0
Locality                                 0
Observed Deaths                      10212
Population                            5280
Expected Deaths                      10212
Potentially Excess Deaths            10212
Percent Potentially Excess Deaths    10212
dtype: int64

In [8]:
def Chamber_of_nulls(df,target,type='mean'):
    columns_with_null = df.columns[df.isnull().any()]
    segments=df[target].unique()
    for i in segments:

        filtered_rows = df[df[target] == i]
        for j in columns_with_null:
            if type=='mean':
              new_value = filtered_rows[j].mean()
            elif type=='mode':
              new_value = filtered_rows[j].mode()
            elif type=='median':
              new_value = filtered_rows[j].median()

            filtered_null_rows = filtered_rows[filtered_rows[j].isna()]
            df.loc[filtered_null_rows.index, j] = new_value
    return df

In [9]:
feature='Cause of Death'
df=Chamber_of_nulls(df, feature)

In [17]:
df = df.drop('State FIPS Code', axis=1)

In [18]:
df.head()

Year Cause of Death    State  HHS Region Age Range   Benchmark  \
0  2005         Cancer  Alabama           4      0-49  2005 Fixed   
1  2005         Cancer  Alabama           4      0-49  2005 Fixed   
2  2005         Cancer  Alabama           4      0-49  2005 Fixed   
3  2005         Cancer  Alabama           4      0-49  2010 Fixed   
4  2005         Cancer  Alabama           4      0-49  2010 Fixed   

          Locality  Observed Deaths  Population  Expected Deaths  \
0              All            756.0   3148377.0            451.0   
1     Metropolitan            556.0   2379871.0            341.0   
2  Nonmetropolitan            200.0    768506.0            111.0   
3              All            756.0   3148377.0            421.0   
4     Metropolitan            556.0   2379871.0            318.0   

   Potentially Excess Deaths  Percent Potentially Excess Deaths  
0                      305.0                               40.3  
1                      217.0                               39.0  
2                       89.0                               44.5  
3                      335.0                               44.3  
4                      238.0                               42.8

In [19]:
df.shape

(205920, 12)

In [20]:
df.isnull().sum()

Year                                 0
Cause of Death                       0
State                                0
HHS Region                           0
Age Range                            0
Benchmark                            0
Locality                             0
Observed Deaths                      0
Population                           0
Expected Deaths                      0
Potentially Excess Deaths            0
Percent Potentially Excess Deaths    0
dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205920 entries, 0 to 205919
Data columns (total 12 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   Year                               205920 non-null  int64  
 1   Cause of Death                     205920 non-null  object 
 2   State                              205920 non-null  object 
 3   HHS Region                         205920 non-null  int64  
 4   Age Range                          205920 non-null  object 
 5   Benchmark                          205920 non-null  object 
 6   Locality                           205920 non-null  object 
 7   Observed Deaths                    205920 non-null  float64
 8   Population                         205920 non-null  float64
 9   Expected Deaths                    205920 non-null  float64
 10  Potentially Excess Deaths          205920 non-null  float64
 11  Percent Potentially Excess Deaths  2059

In [23]:
df['Benchmark'].unique()

array(['2005 Fixed', '2010 Fixed', 'Floating'], dtype=object)

In [24]:
from sklearn.preprocessing import LabelEncoder                                # it helps to convert object to integer
label_encoder = LabelEncoder()


df['Cause of Death'] = label_encoder.fit_transform(df['Cause of Death'])
df['State'] = label_encoder.fit_transform(df['State'])
df['Age Range'] = label_encoder.fit_transform(df['Age Range'])
df['Benchmark'] = label_encoder.fit_transform(df['Benchmark'])
df['Locality'] = label_encoder.fit_transform(df['Locality'])

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205920 entries, 0 to 205919
Data columns (total 12 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   Year                               205920 non-null  int64  
 1   Cause of Death                     205920 non-null  int64  
 2   State                              205920 non-null  int64  
 3   HHS Region                         205920 non-null  int64  
 4   Age Range                          205920 non-null  int64  
 5   Benchmark                          205920 non-null  int64  
 6   Locality                           205920 non-null  int64  
 7   Observed Deaths                    205920 non-null  float64
 8   Population                         205920 non-null  float64
 9   Expected Deaths                    205920 non-null  float64
 10  Potentially Excess Deaths          205920 non-null  float64
 11  Percent Potentially Excess Deaths  2059

In [26]:
target = 'Cause of Death'

In [28]:
X= df.loc[:,df.columns != target]                                               # every columns goes to X except the target

Y = df[target]                                                                  # target column is Y

In [29]:
from sklearn.model_selection import train_test_split                            # X and Y is spited into text and train segments

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2)

#RandomForest Classifier

In [30]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_jobs=-1)

clf.fit(X_train, Y_train)                                                       # Fitting the training segment into the model

y_pred = clf.predict(X_test)                                                    # the model is predicting the test cases

In [31]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[8179    0   22    0   12]
 [   0 7714    0  342  201]
 [  39    0 8124    0   45]
 [   0  322    0 7862   21]
 [  14   95   40   21 8131]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      8213
           1       0.95      0.93      0.94      8257
           2       0.99      0.99      0.99      8208
           3       0.96      0.96      0.96      8205
           4       0.97      0.98      0.97      8301

    accuracy                           0.97     41184
   macro avg       0.97      0.97      0.97     41184
weighted avg       0.97      0.97      0.97     41184

Accurecy:  0.9714937839937839


#ADABoost Classifier

In [32]:
from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier()

ada.fit(X_train, Y_train)

y_pred = ada.predict(X_test)

In [33]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[4321    2 3622  135  133]
 [ 252 2540  400 2508 2557]
 [1452   95 3984  505 2172]
 [ 413 1596  173 4248 1775]
 [ 391  993  760  743 5414]]
              precision    recall  f1-score   support

           0       0.63      0.53      0.57      8213
           1       0.49      0.31      0.38      8257
           2       0.45      0.49      0.46      8208
           3       0.52      0.52      0.52      8205
           4       0.45      0.65      0.53      8301

    accuracy                           0.50     41184
   macro avg       0.51      0.50      0.49     41184
weighted avg       0.51      0.50      0.49     41184

Accurecy:  0.4979360916860917


#GradientBoosting Classifier

In [ ]:

from sklearn.ensemble import GradientBoostingClassifier

GBC = GradientBoostingClassifier()

GBC.fit(X_train, Y_train)

y_pred = ada.predict(X_test)

In [ ]:

print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

#KN Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)

y_pred=knn.predict(X_test)

In [ ]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

#Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train, Y_train)

y_pred = gnb.predict(X_test)

In [ ]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

#SVM Classifier

In [ ]:
from sklearn.svm import SVC

svm_classifier = SVC(kernel='linear')

svm_classifier.fit(X_train, Y_train)

y_pred = svm_classifier.predict(X_test)

In [ ]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

#Logitic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 0)
lr.fit(X_train, Y_train)
y_pred = lr.predict(X_test)

In [ ]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

#CAT Boosting

In [ ]:
from catboost import CatBoostClassifier

# Create a CatBoostClassifier
model = CatBoostClassifier()

# Fit the model to the training data
model.fit(X_train, Y_train)

# Make predictions on test data
y_pred = model.predict(X_test)

In [ ]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))