<a href="https://colab.research.google.com/github/Ahtesham-Ibne-Mostafa/Machine_Etymology/blob/main/EEG_HMC_underscore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

dataset=pd.read_csv('https://raw.githubusercontent.com/Ahtesham-Ibne-Mostafa/Gold_Mining/main/data.csv')


In [2]:
dataset.head()

Unnamed: 0 Sleep_Stage  MeanP_Alpha_F4  MedianF_Alpha_F4  MeanF_Alpha_F4  \
0           0           W         0.00051           8.74146        18.48195   
1           1           W         0.00040          10.24000        17.48293   
2           2           W         0.00036           9.74049        17.98244   
3           3           W         0.00035          10.11512        17.60780   
4           4           W         0.00033           9.74049        17.60780   

   Spectral Edge_Alpha_F4  PeakF_Alpha_F4  MeanP_Beta_F4  MedianF_Beta_F4  \
0                17.48293         8.24195        0.00071         19.73073   
1                16.85854        10.61463        0.00051         17.23317   
2                17.48293         8.74146        0.00047         17.60780   
3                17.10829         9.61561        0.00047         17.35805   
4                17.23317         8.11707        0.00043         17.23317   

   MeanF_Beta_F4  ...  MeanP_Delta_O2  MedianF_Delta_O2  MeanF_Delta_O2  \
0       29.84585  ...         0.00724           0.74927         3.87122   
1       26.34927  ...         0.00723           0.49951         3.74634   
2       25.47512  ...         0.00230           0.62439         5.24488   
3       26.47415  ...         0.00091           0.87415         6.61854   
4       25.84976  ...         0.00175           0.49951         5.74439   

   Spectral Edge_Delta_O2  PeakF_Delta_O2  MeanP_Gamma_O2  MedianF_Gamma_O2  \
0                 1.99805         0.87415        0.000210          35.21561   
1                 1.24878         0.49951        0.000095          34.34146   
2                 2.12293         0.62439        0.000074          34.59122   
3                 3.12195         0.62439        0.000082          32.46829   
4                 2.24780         0.49951        0.000077          33.59220   

   MeanF_Gamma_O2  Spectral Edge_Gamma_O2  PeakF_Gamma_O2  
0        42.20878                49.95122        49.95122  
1        43.33268                49.95122        49.95122  
2        45.95512                49.95122        49.95122  
3        43.95707                49.95122        49.95122  
4        44.83122                49.95122        49.95122  

[5 rows x 77 columns]

In [3]:
dataset.shape

(108451, 77)

In [4]:
X=dataset.loc[:,dataset.columns != 'Sleep_Stage']
Y=dataset['Sleep_Stage']


In [5]:
print(Y)

0          W
1          W
2          W
3          W
4          W
          ..
108446    N1
108447    N1
108448    N1
108449     W
108450     W
Name: Sleep_Stage, Length: 108451, dtype: object


In [6]:
from sklearn.preprocessing  import StandardScaler

x=StandardScaler().fit_transform(X)

In [7]:
print(X)

        Unnamed: 0  MeanP_Alpha_F4  MedianF_Alpha_F4  MeanF_Alpha_F4  \
0                0         0.00051           8.74146        18.48195   
1                1         0.00040          10.24000        17.48293   
2                2         0.00036           9.74049        17.98244   
3                3         0.00035          10.11512        17.60780   
4                4         0.00033           9.74049        17.60780   
...            ...             ...               ...             ...   
108446      108446         0.00031          10.11512        17.48293   
108447      108447         0.00042           9.99024        16.35902   
108448      108448         0.00040           9.86537        15.73463   
108449      108449         0.00051          10.11512        17.85756   
108450      108450         0.00128          10.61463        21.47902   

        Spectral Edge_Alpha_F4  PeakF_Alpha_F4  MeanP_Beta_F4  \
0                     17.48293         8.24195        0.00071   
1    

In [8]:
from sklearn.model_selection import train_test_split 

X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2, random_state=0)

In [9]:
# Training

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score


for i in range(1,201):

    clf = GradientBoostingClassifier(n_estimators = i)

    clf.fit(X_train,Y_train)

    y_pred = clf.predict(X_test)

    print('Estimator: ',i,'__Accuracy: ',accuracy_score(Y_test,y_pred)) # model prediction

Estimator:  1 __Accuracy:  0.36379143423539717
Estimator:  2 __Accuracy:  0.42967129224102163


KeyboardInterrupt: ignored

In [ ]:

for i in range(1,201):

    clf = GradientBoostingClassifier(max_depth = i)

    clf.fit(X_train,Y_train)

    y_pred = clf.predict(X_test)

    print('Max Depth: ',i,'__Accuracy: ',accuracy_score(Y_test,y_pred)) # model prediction

Max Depth:  1 __Accuracy:  0.6617952146051358


KeyboardInterrupt: ignored

In [10]:
print(accuracy_score(Y_test,y_pred)) # model prediction

0.42967129224102163


In [11]:
# Accuracy Mactrics

from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))
     

[[   0 2224    0    0  144]
 [   0 7858    0    0   33]
 [   0 4254    0    0    0]
 [   0 3357    0    0   17]
 [   0 2342    0    0 1462]]


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

          N1       0.00      0.00      0.00      2368
          N2       0.39      1.00      0.56      7891
          N3       0.00      0.00      0.00      4254
           R       0.00      0.00      0.00      3374
           W       0.88      0.38      0.54      3804

    accuracy                           0.43     21691
   macro avg       0.26      0.28      0.22     21691
weighted avg       0.30      0.43      0.30     21691



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
