<a href="https://colab.research.google.com/github/Ahtesham-Ibne-Mostafa/Machine_Etymology/blob/main/EEG_HMC_underscore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [8]:
dataset=pd.read_csv('new.csv')

In [9]:
dataset.head()

Sleep_Stage  MeanP_Alpha_F4  MedianF_Alpha_F4  MeanF_Alpha_F4  \
0           W         0.00051           8.74146        18.48195   
1           W         0.00040          10.24000        17.48293   
2           W         0.00036           9.74049        17.98244   
3           W         0.00035          10.11512        17.60780   
4           W         0.00033           9.74049        17.60780   

   Spectral Edge_Alpha_F4  PeakF_Alpha_F4  MeanP_Beta_F4  MedianF_Beta_F4  \
0                17.48293         8.24195        0.00071         19.73073   
1                16.85854        10.61463        0.00051         17.23317   
2                17.48293         8.74146        0.00047         17.60780   
3                17.10829         9.61561        0.00047         17.35805   
4                17.23317         8.11707        0.00043         17.23317   

   MeanF_Beta_F4  Spectral Edge_Beta_F4  ...  MeanP_DTR_O2  MedianF_DTR_O2  \
0       29.84585               33.84195  ...      18.56410         0.16667   
1       26.34927               29.34634  ...      28.92000         0.08511   
2       25.47512               28.22244  ...       9.58333         0.10870   
3       26.47415               28.72195  ...       3.64000         0.14286   
4       25.84976               28.09756  ...       7.29167         0.08511   

   MeanF_DTR_O2  Spectral Edge_DTR_O2  PeakF_DTR_O2  MeanP_DTABR_O2  \
0       0.28704               0.18605       0.38889         8.67045   
1       0.27523               0.11111       0.16667        12.26230   
2       0.39252               0.19101       0.12195         4.61818   
3       0.50000               0.28409       0.17241         1.90164   
4       0.43396               0.20454       0.16667         3.49123   

   MedianF_DTABR_O2  MeanF_DTABR_O2  Spectral Edge_DTABR_O2  PeakF_DTABR_O2  
0           0.16342         0.34406                 0.23288         0.09843  
1           0.22271         0.38187                 0.25575         0.11618  
2           0.22368         0.42693                 0.28571         0.18182  
3           0.24454         0.44044                 0.30214         0.15962  
4           0.22174         0.42817                 0.28342         0.11336  

[5 rows x 121 columns]

In [10]:
dataset.shape

(108451, 121)

In [11]:



X=dataset.loc[:,dataset.columns != 'Sleep_Stage']
Y=dataset['Sleep_Stage']


In [12]:
print(Y)

0          W
1          W
2          W
3          W
4          W
          ..
108446    N1
108447    N1
108448    N1
108449     W
108450     W
Name: Sleep_Stage, Length: 108451, dtype: object


In [13]:
from sklearn.preprocessing  import StandardScaler

x=StandardScaler().fit_transform(X)

In [15]:
print(X)

        MeanP_Alpha_F4  MedianF_Alpha_F4  MeanF_Alpha_F4  \
0              0.00051           8.74146        18.48195   
1              0.00040          10.24000        17.48293   
2              0.00036           9.74049        17.98244   
3              0.00035          10.11512        17.60780   
4              0.00033           9.74049        17.60780   
...                ...               ...             ...   
108446         0.00031          10.11512        17.48293   
108447         0.00042           9.99024        16.35902   
108448         0.00040           9.86537        15.73463   
108449         0.00051          10.11512        17.85756   
108450         0.00128          10.61463        21.47902   

        Spectral Edge_Alpha_F4  PeakF_Alpha_F4  MeanP_Beta_F4  \
0                     17.48293         8.24195        0.00071   
1                     16.85854        10.61463        0.00051   
2                     17.48293         8.74146        0.00047   
3                  

In [17]:
from sklearn.model_selection import train_test_split 

X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2, random_state=0)

In [18]:
# Training

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score


for i in range(1,201):

    clf = GradientBoostingClassifier(n_estimators = i)

    clf.fit(X_train,Y_train)

    y_pred = clf.predict(X_test)

    print('Estimator: ',i,'__Accuracy: ',accuracy_score(Y_test,y_pred)) # model prediction

Estimator:  1 __Accuracy:  0.36379143423539717


KeyboardInterrupt: 

In [19]:

for i in range(1,201):

    clf = GradientBoostingClassifier(max_depth = i)

    clf.fit(X_train,Y_train)

    y_pred = clf.predict(X_test)

    print('Max Depth: ',i,'__Accuracy: ',accuracy_score(Y_test,y_pred)) # model prediction

Max Depth:  1 __Accuracy:  0.6651145636439076


KeyboardInterrupt: 

In [20]:
print(accuracy_score(Y_test,y_pred)) # model prediction

0.6651145636439076


In [21]:
# Accuracy Mactrics

from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))

[[ 363  830   59  439  677]
 [ 118 6258  861  377  277]
 [   4 1280 2932    7   31]
 [ 142 1199  102 1784  147]
 [ 183  358   73  100 3090]]
              precision    recall  f1-score   support

          N1       0.45      0.15      0.23      2368
          N2       0.63      0.79      0.70      7891
          N3       0.73      0.69      0.71      4254
           R       0.66      0.53      0.59      3374
           W       0.73      0.81      0.77      3804

    accuracy                           0.67     21691
   macro avg       0.64      0.60      0.60     21691
weighted avg       0.65      0.67      0.65     21691

