<a href="https://colab.research.google.com/github/Ahtesham-Ibne-Mostafa/Machine_Etymology/blob/main/University_Ranking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [141]:
import pandas as pd
import numpy as np
import math

In [142]:
df=pd.read_csv('https://raw.githubusercontent.com/Ahtesham-Ibne-Mostafa/Machine_Etymology/main/Datasets/World%20University%20Rankings%202023.csv')                       # Reading Csv file with pandas

In [143]:
df.head()                                                              # shows the first 5 rows of the csv file

University Rank                     Name of University        Location  \
0               1                   University of Oxford  United Kingdom   
1               2                     Harvard University   United States   
2               3                University of Cambridge  United Kingdom   
3               3                    Stanford University   United States   
4               5  Massachusetts Institute of Technology   United States   

  No of student  No of student per staff International Student  \
0        20,965                     10.6                   42%   
1        21,887                      9.6                   25%   
2        20,185                     11.3                   39%   
3        16,164                      7.1                   24%   
4        11,415                      8.2                   33%   

  Female:Male Ratio OverAll Score  Teaching Score  Research Score  \
0           48 : 52          96.4            92.3            99.7   
1           50 : 50          95.2            94.8            99.0   
2           47 : 53          94.8            90.9            99.5   
3           46 : 54          94.8            94.2            96.7   
4           40 : 60          94.2            90.7            93.6   

   Citations Score  Industry Income Score  International Outlook Score  
0             99.0                   74.9                         96.2  
1             99.3                   49.5                         80.5  
2             97.0                   54.2                         95.8  
3             99.8                   65.0                         79.8  
4             99.8                   90.9                         89.3

In [144]:

df.columns                                                        #---> returns all names of columns as a list


Index(['University Rank', 'Name of University', 'Location', 'No of student',
       'No of student per staff', 'International Student', 'Female:Male Ratio',
       'OverAll Score', 'Teaching Score', 'Research Score', 'Citations Score',
       'Industry Income Score', 'International Outlook Score'],
      dtype='object')

In [145]:
df.describe()                                                #--> Statistical descriptions of different types of data

No of student per staff  Teaching Score  Research Score  \
count              2208.000000     1799.000000     1799.000000   
mean                 19.000408       27.018010       23.016898   
std                  12.132224       13.282243       16.763819   
min                   0.400000       11.600000        7.400000   
25%                  12.600000       18.000000       11.300000   
50%                  16.600000       22.700000       17.000000   
75%                  22.200000       31.850000       28.900000   
max                 232.200000       94.800000       99.700000   

       Citations Score  Industry Income Score  International Outlook Score  
count      1799.000000            1799.000000                  1799.000000  
mean         48.495887              47.104558                    46.880378  
std          27.967185              15.093682                    22.582401  
min           0.800000              36.900000                    14.100000  
25%          23.100000              37.800000                    27.900000  
50%          47.200000              40.500000                    42.100000  
75%          72.350000              48.300000                    62.100000  
max         100.000000             100.000000                    99.700000

In [146]:
df.info()                                                     # shows Non null value and data type(string == object)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2341 entries, 0 to 2340
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   University Rank              2341 non-null   object 
 1   Name of University           2233 non-null   object 
 2   Location                     2047 non-null   object 
 3   No of student                2209 non-null   object 
 4   No of student per staff      2208 non-null   float64
 5   International Student        2209 non-null   object 
 6   Female:Male Ratio            2128 non-null   object 
 7   OverAll Score                1799 non-null   object 
 8   Teaching Score               1799 non-null   float64
 9   Research Score               1799 non-null   float64
 10  Citations Score              1799 non-null   float64
 11  Industry Income Score        1799 non-null   float64
 12  International Outlook Score  1799 non-null   float64
dtypes: float64(6), obj

In [147]:
df.shape                                                      # shows rows and columns

(2341, 13)

In [148]:
df = df.drop('Location', axis=1)                            # drops the column

In [149]:
df=df.dropna().reset_index(drop=True)                           # drops all the null values rows and resets the index number

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1621 entries, 0 to 1620
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   University Rank              1621 non-null   object 
 1   Name of University           1621 non-null   object 
 2   No of student                1621 non-null   object 
 3   No of student per staff      1621 non-null   float64
 4   International Student        1621 non-null   object 
 5   Female:Male Ratio            1621 non-null   object 
 6   OverAll Score                1621 non-null   object 
 7   Teaching Score               1621 non-null   float64
 8   Research Score               1621 non-null   float64
 9   Citations Score              1621 non-null   float64
 10  Industry Income Score        1621 non-null   float64
 11  International Outlook Score  1621 non-null   float64
dtypes: float64(6), object(6)
memory usage: 152.1+ KB


In [151]:
target='University Rank'

In [152]:

df[target].unique()                         # shows the unique values of a column

array(['1', '2', '3', '5', '6', '7', '8', '9', '10', '11', '13', '14',
       '15', '18', '19', '20', '21', '22', '23', '24', '25', '26', '28',
       '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '40',
       '41', '42', '43', '44', '46', '47', '48', '49', '50', '51', '52',
       '53', '54', '57', '59', '60', '62', '63', '64', '65', '66', '68',
       '69', '70', '71', '73', '75', '76', '77', '78', '79', '80', '82',
       '85', '86', '88', '89', '90', '91', '93', '94', '95', '98', '99',
       '101', '104', '106', '107', '108', '110', '112', '113', '114',
       '117', '119', '121', '122', '123', '124', '126', '127', '128',
       '130', '131', '133', '134', '136', '137', '139', '144', '145',
       '147', '148', '151', '154', '155', '156', '160', '161', '163',
       '166', '168', '170', '174', '175', '176', '180', '181', '182',
       '183', '186', '187', '189', '191', '192', '194', '196', '198',
       '201–250', '251–300', '301–350', '351–400', '401–500', '501–600'

In [153]:
from sklearn.preprocessing import LabelEncoder                                # it helps to convert object to integer
label_encoder = LabelEncoder()


df['University Rank'] = label_encoder.fit_transform(df['University Rank'])
df['Name of University'] = label_encoder.fit_transform(df['Name of University'])
df['No of student'] = label_encoder.fit_transform(df['No of student'])
df['International Student'] = label_encoder.fit_transform(df['International Student'])
df['Female:Male Ratio'] = label_encoder.fit_transform(df['Female:Male Ratio'])
df['OverAll Score'] = label_encoder.fit_transform(df['OverAll Score'])

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1621 entries, 0 to 1620
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   University Rank              1621 non-null   int32  
 1   Name of University           1621 non-null   int32  
 2   No of student                1621 non-null   int32  
 3   No of student per staff      1621 non-null   float64
 4   International Student        1621 non-null   int32  
 5   Female:Male Ratio            1621 non-null   int32  
 6   OverAll Score                1621 non-null   int32  
 7   Teaching Score               1621 non-null   float64
 8   Research Score               1621 non-null   float64
 9   Citations Score              1621 non-null   float64
 10  Industry Income Score        1621 non-null   float64
 11  International Outlook Score  1621 non-null   float64
dtypes: float64(6), int32(6)
memory usage: 114.1 KB


In [155]:
X= df.loc[:,df.columns != target]                                               # every columns goes to X except the target

Y = df[target]                                                                  # target column is Y

In [156]:
from sklearn.model_selection import train_test_split                            # X and Y is spited into text and train segments

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2)

RandomForest Classifier

In [157]:

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_jobs=-1)

clf.fit(X_train, Y_train)                                                       # Fitting the training segment into the model

y_pred = clf.predict(X_test)                                                    # the model is predicting the test cases

In [158]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[ 0  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           2       1.00      1.00      1.00        30
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         2
           5       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         0
          15       1.00      1.00      1.00        42
          17       0.00      0.00      0.00         0
          19       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         1
          26       0.00      0.00

C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_cla

ADABoost Classifier

In [159]:
from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier()

ada.fit(X_train, Y_train)

y_pred = ada.predict(X_test)

In [160]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[30  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
              precision    recall  f1-score   support

           2       1.00      1.00      1.00        30
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         2
           8       0.00      0.00      0.00         1
          15       1.00      1.00      1.00        42
          19       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         1
          26       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         1
          30       0.05      1.00      0.09         1
          35       0.00      0.00      0.00         1
          37       1.00      1.00      1.00        62
          41       0.00      0.00      0.00         0
          52       0.00      0.00

C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_cla

GradientBoosting Classifier

In [161]:
from sklearn.ensemble import GradientBoostingClassifier

GBC = GradientBoostingClassifier()

GBC.fit(X_train, Y_train)

y_pred = ada.predict(X_test)

In [162]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[30  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
              precision    recall  f1-score   support

           2       1.00      1.00      1.00        30
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         2
           8       0.00      0.00      0.00         1
          15       1.00      1.00      1.00        42
          19       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         1
          26       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         1
          30       0.05      1.00      0.09         1
          35       0.00      0.00      0.00         1
          37       1.00      1.00      1.00        62
          41       0.00      0.00      0.00         0
          52       0.00      0.00

C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_cla

KN Classifier

In [163]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)

y_pred=knn.predict(X_test)

C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [164]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[12  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
              precision    recall  f1-score   support

           2       0.11      0.40      0.18        30
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         0
          14       0.00      0.00      0.00         0
          15       0.20      0.43      0.27        42
          19       0.00      0.00      0.00         1
          22       0.00      0.00      0.00         0
          24       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         1
          26       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         1
          29       0.00      0.00

C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_cla

Naive Bayes

In [165]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train, Y_train)

y_pred = gnb.predict(X_test)

In [166]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[30  0  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 [ 0  2  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  1]
 [ 0  0  0 ...  0  0  1]
 [ 0  0  0 ...  0  0  1]]
              precision    recall  f1-score   support

           2       1.00      1.00      1.00        30
           3       0.33      1.00      0.50         1
           4       0.00      0.00      0.00         2
           8       0.00      0.00      0.00         1
          15       1.00      1.00      1.00        42
          19       0.00      0.00      0.00         1
          22       0.00      0.00      0.00         0
          24       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         1
          26       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         0
          30       1.00      1.00      1.00         1
          35       1.00      1.00      1.00         1
          37       1.00      1.00

C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_cla

SVM Classifier

In [167]:
from sklearn.svm import SVC

svm_classifier = SVC(kernel='linear')

svm_classifier.fit(X_train, Y_train)

y_pred = svm_classifier.predict(X_test)

In [168]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[30  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
              precision    recall  f1-score   support

           2       1.00      1.00      1.00        30
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         0
          15       1.00      1.00      1.00        42
          19       0.00      0.00      0.00         1
          22       0.00      0.00      0.00         0
          23       0.00      0.00      0.00         0
          24       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         1
          26       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         1
          28       0.00      0.00

C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_cla

Logitic Regression

In [169]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 0)
lr.fit(X_train, Y_train)
y_pred = lr.predict(X_test)

C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [170]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[0 0 0 ... 0 0 0]
 [0 7 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           2       0.15      0.23      0.18        30
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         2
           8       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         0
          15       0.34      0.64      0.45        42
          19       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         1
          26       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         1
          30       0.00      0.00      0.00         1
          35       0.00      0.00      0.00         1
          36       0.00      0.00      0.00         0
          37   

C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_cla

CAT Boosting

In [171]:
!pip install catboost

In [172]:
from catboost import CatBoostClassifier

# Create a CatBoostClassifier
model = CatBoostClassifier()

# Fit the model to the training data
model.fit(X_train, Y_train)

# Make predictions on test data
y_pred = model.predict(X_test)

Learning rate set to 0.08018
0:	learn: 3.2460209	total: 204ms	remaining: 3m 24s
1:	learn: 2.9573915	total: 421ms	remaining: 3m 29s
2:	learn: 2.6520912	total: 621ms	remaining: 3m 26s
3:	learn: 2.4301667	total: 810ms	remaining: 3m 21s
4:	learn: 2.2111298	total: 910ms	remaining: 3m 1s
5:	learn: 2.0931683	total: 1.1s	remaining: 3m 1s
6:	learn: 1.9590739	total: 1.27s	remaining: 3m
7:	learn: 1.8478800	total: 1.46s	remaining: 3m 1s
8:	learn: 1.6983419	total: 1.64s	remaining: 3m
9:	learn: 1.6166959	total: 1.82s	remaining: 3m
10:	learn: 1.5547688	total: 2s	remaining: 3m
11:	learn: 1.4992023	total: 2.19s	remaining: 3m
12:	learn: 1.4379693	total: 2.38s	remaining: 3m
13:	learn: 1.3929743	total: 2.58s	remaining: 3m 2s
14:	learn: 1.3487971	total: 2.77s	remaining: 3m 1s
15:	learn: 1.3030485	total: 2.97s	remaining: 3m 2s
16:	learn: 1.2611253	total: 3.16s	remaining: 3m 2s
17:	learn: 1.2281775	total: 3.35s	remaining: 3m 2s
18:	learn: 1.1815776	total: 3.54s	remaining: 3m 2s
19:	learn: 1.1421824	total: 3.

In [173]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test,y_pred))
print("Accurecy: ",accuracy_score(Y_test, y_pred))

[[ 0  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  1]
 [ 0  0  0 ...  0  0  0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           2       1.00      1.00      1.00        30
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         2
           5       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         1
          10       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          14       0.00      0.00      0.00         0
          15       1.00      1.00      1.00        42
          17       0.00      0.00      0.00         0
          19       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         1
          25       0.00      0.00

C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahtes\anaconda3\lib\site-packages\sklearn\metrics\_cla